Repository chartdb/chartdb, pull requests merged in 2024-12, with the labels that each got.

#453 chore(main): release 1.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#472 feat(CockroachDB): Add CockroachDB support
  src/assets/cockroachdb_logo.png
  src/assets/cockroachdb_logo_2.png
  src/assets/cockroachdb_logo_dark.png
  src/dialogs/create-diagram-dialog/select-database/example-option.tsx
  src/dialogs/create-diagram-dialog/select-database/select-database-content.tsx
  src/lib/data/data-types/data-types.ts
  src/lib/data/export-metadata/export-sql-script.ts
  src/lib/data/import-metadata/scripts/cockroachdb-script.ts
  src/lib/data/import-metadata/scripts/scripts.ts
  src/lib/databases.ts
  src/lib/domain/database-clients.ts
  src/lib/domain/database-edition.ts
  src/lib/domain/database-type.ts
  src/lib/domain/db-dependency.ts
  src/lib/domain/db-schema.ts
Labels: enhancement

#480 fix(sql-server import) nullable should be boolean instead of string
  src/lib/data/import-metadata/scripts/sqlserver-script.ts
Labels: bug

#482 Update README.md
  README.md
Labels: documentation

#483 chore(main): release 1.5.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending
