Repository chartdb/chartdb, pull requests merged in 2024-08, with the labels that each got.

#91 feat: optimize and improve dockerfile
  .dockerignore
  Dockerfile
  README.md
Labels: Infra

#100 fix pg - FK import query
  src/lib/data/import-metadata/scripts/postgres-script.ts
Labels: bug

#104 fix README.md support dark theme
  README.md
Labels: documentation

#106 chore: update README.md add indication we support Supbadse + TimescaleDB
  README.md
Labels: documentation
