Repository chartdb/chartdb, pull requests merged in 2024-11, with the labels that each got.

#319 chore(main): release 1.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#320 chore(main): release 1.0.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#367 chore(editable titles): improve title name edit interaction
  src/globals.css
  src/i18n/locales/de.ts
  src/i18n/locales/en.ts
  src/i18n/locales/es.ts
  src/i18n/locales/fr.ts
  src/i18n/locales/hi.ts
  src/i18n/locales/ja.ts
  src/i18n/locales/ko_KR.ts
  src/i18n/locales/pt_BR.ts
  src/i18n/locales/uk.ts
  src/pages/editor-page/side-panel/tables-section/table-list/table-list-item/table-list-item-header/table-list-item-header.tsx
  src/pages/editor-page/top-navbar/diagram-name.tsx
  src/pages/editor-page/top-navbar/top-navbar.tsx
Labels: enhancement

#376 (i18n): Added Russian language V2
  src/i18n/i18n.ts
  src/i18n/locales/ru.ts
Labels: Translation

#373 Added Snap to grid functionality, (toggle + hold shift to snap to grid) issue: #225
  src/i18n/locales/de.ts
  src/i18n/locales/en.ts
  src/i18n/locales/es.ts
  src/i18n/locales/fr.ts
  src/i18n/locales/hi.ts
  src/i18n/locales/ja.ts
  src/i18n/locales/ko_KR.ts
  src/i18n/locales/pt_BR.ts
  src/i18n/locales/ru.ts
  src/i18n/locales/uk.ts
  src/pages/editor-page/canvas/canvas.tsx
Labels: team need to check

#372 Adds missing spanish translations
  src/i18n/locales/es.ts
Labels: Translation

#365 feat(share): add sharing capabilities to import and export diagrams
  package-lock.json
  package.json
  src/components/alert/alert.tsx
  src/components/file-uploader/file-uploader.tsx
  src/context/dialog-context/dialog-context.tsx
  src/context/dialog-context/dialog-provider.tsx
  src/dialogs/create-diagram-dialog/select-database/select-database.tsx
  src/dialogs/export-diagram-dialog/export-diagram-dialog.tsx
  src/dialogs/import-diagram-dialog/import-diagram-dialog.tsx
  src/i18n/locales/de.ts
  src/i18n/locales/en.ts
  src/i18n/locales/es.ts
  src/i18n/locales/fr.ts
  src/i18n/locales/hi.ts
  src/i18n/locales/ja.ts
  src/i18n/locales/ko_KR.ts
  src/i18n/locales/pt_BR.ts
  src/i18n/locales/ru.ts
  src/i18n/locales/uk.ts
  src/lib/data/data-types/data-types.ts
  src/lib/domain/db-dependency.ts
  src/lib/domain/db-field.ts
  src/lib/domain/db-index.ts
  src/lib/domain/db-relationship.ts
  src/lib/domain/db-table.ts
  src/lib/domain/diagram.ts
  src/lib/export-import-utils.ts
  src/lib/utils.ts
  src/pages/editor-page/top-navbar/top-navbar.tsx
  src/templates-data/template-utils.ts
Labels: enhancement

#388 fix(sql export): make loading for export interactive
  src/components/code-snippet/code-snippet.tsx
  src/dialogs/export-sql-dialog/export-sql-dialog.tsx
  src/lib/data/export-metadata/export-sql-script.ts
  tailwind.config.js
Labels: enhancement

#385 feat: Add simplified chinese
  src/i18n/i18n.ts
  src/i18n/locales/zh_CN.ts
Labels: Translation

#380 fix(i18n): Fixed part of RU lang introduced in #365 feat(share)
  src/i18n/locales/ru.ts
Labels: Translation

#356 feat: added traditional chinese language translation
  src/i18n/i18n.ts
  src/i18n/locales/zh_TW.ts
Labels: Translation

#392 feat(add templates): add five more templates
  src/assets/templates/gravity-db-dark.png
  src/assets/templates/gravity-db.png
  src/assets/templates/koel-db-dark.png
  src/assets/templates/koel-db.png
  src/assets/templates/laravel-permission-db-dark.png
  src/assets/templates/laravel-permission-db.png
  src/assets/templates/laravel-spark-db-dark.png
  src/assets/templates/laravel-spark-db.png
  src/assets/templates/voyager-db-dark.png
  src/assets/templates/voyager-db.png
  src/templates-data/templates-data.ts
  src/templates-data/templates/gravity-db.ts
  src/templates-data/templates/koel-db.ts
  src/templates-data/templates/laravel-permission-db.ts
  src/templates-data/templates/laravel-spark-db.ts
  src/templates-data/templates/voyager-db.ts
Labels: enhancement

#364 chore(main): release 1.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#395 fix(canvas): fix auto zoom on diagram load
  src/pages/editor-page/canvas/canvas.tsx
Labels: ux

#390 fix(AI exports): add cahching layer to SQL exports
  src/lib/data/export-metadata/export-sql-cache.ts
  src/lib/data/export-metadata/export-sql-script.ts
  src/lib/utils.ts
Labels: enhancement

#403 docs: update license reference
  CONTRIBUTING.md
Labels: documentation

#402 fix(templates): add six more templates
  src/assets/templates/buddypress-dark.png
  src/assets/templates/buddypress.png
  src/assets/templates/comfortable-mexican-sofa-db-dark.png
  src/assets/templates/comfortable-mexican-sofa-db.png
  src/assets/templates/lobsters-db-dark.png
  src/assets/templates/lobsters-db.png
  src/assets/templates/refinerycms-db-dark.png
  src/assets/templates/refinerycms-db.png
  src/assets/templates/snipe-it-db-dark.png
  src/assets/templates/snipe-it-db.png
  src/assets/templates/ticketit-db-dark.png
  src/assets/templates/ticketit-db.png
  src/templates-data/templates-data.ts
  src/templates-data/templates/buddypress-db.ts
  src/templates-data/templates/comfortable-mexican-sofa-db.ts
  src/templates-data/templates/lobsters-db.ts
  src/templates-data/templates/refinerycms-db.ts
  src/templates-data/templates/snipe-it-db.ts
  src/templates-data/templates/ticketit-db.ts
Labels: documentation

#408 fix(templates): add Five more templates (Sylius, Monica, Attendize, SaaS Pegasus & BookStack)
  src/assets/templates/attendize-db-dark.png
  src/assets/templates/attendize-db.png
  src/assets/templates/bookstack-db-dark.png
  src/assets/templates/bookstack-db.png
  src/assets/templates/monica-db-dark.png
  src/assets/templates/monica-db.png
  src/assets/templates/saas-pegasus-db-dark.png
  src/assets/templates/saas-pegasus-db.png
  src/assets/templates/sylius-db-dark.png
  src/assets/templates/sylius-db.png
  src/templates-data/templates-data.ts
  src/templates-data/templates/attendize-db.ts
  src/templates-data/templates/bookstack-db.ts
  src/templates-data/templates/comfortable-mexican-sofa-db.ts
  src/templates-data/templates/monica-db.ts
  src/templates-data/templates/saas-pegasus-db.ts
  src/templates-data/templates/sylius-db.ts
Labels: documentation

#411 fix(i18n): fix language nav: close when lang selected, hide tooltip when lang selected
  src/pages/editor-page/top-navbar/language-nav/language-nav.tsx
Labels: ux

#266 i18n: Create Translations in marathi language
  src/i18n/i18n.ts
  src/i18n/locales/mr.ts
Labels: Translation

#406 feat(i18n): add nepali translations
  src/i18n/i18n.ts
  src/i18n/locales/ne.ts
Labels: Translation

#396 chore(main): release 1.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#315 fix(i18n): add missing Turkish translations
  src/i18n/i18n.ts
  src/i18n/locales/tr.ts
Labels: Translation

#422 fix(export-sql): add unique to export script
  src/lib/data/export-metadata/export-sql-script.ts
Labels: bug

#419 fix(i18n): update korean for 1.2.0
  src/i18n/locales/ko_KR.ts
Labels: Translation

#331 i18n: add bahasa indonesia translation
  src/i18n/i18n.ts
  src/i18n/locales/id_ID.ts
Labels: Translation

#439 feat: collapsible sidebar on desktop view
  src/context/keyboard-shortcuts-context/keyboard-shortcuts-provider.tsx
  src/context/keyboard-shortcuts-context/keyboard-shortcuts.ts
  src/context/layout-context/layout-context.tsx
  src/context/layout-context/layout-provider.tsx
  src/pages/editor-page/editor-desktop-layout.tsx
  src/pages/editor-page/top-navbar/top-navbar.tsx
Labels: enhancement

#435 feat(i18n): add Vietnamese translations
  src/i18n/i18n.ts
  src/i18n/locales/vi.ts
Labels: Translation

#417 chore(main): release 1.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#446 Update Docker Instructions in README.md
  README.md
Labels: documentation

#449 chore(main): release 1.3.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#452 feat(add templates): add six more templates
  src/assets/templates/cachet-db-dark.png
  src/assets/templates/cachet-db.png
  src/assets/templates/canvas-db-dark.png
  src/assets/templates/canvas-db.png
  src/assets/templates/doorkeeper-db-dark.png
  src/assets/templates/doorkeeper-db.png
  src/assets/templates/flipper-db-dark.png
  src/assets/templates/flipper-db.png
  src/assets/templates/orchid-db-dark.png
  src/assets/templates/orchid-db.png
  src/assets/templates/taggit-db-dark.png
  src/assets/templates/taggit-db.png
  src/templates-data/templates-data.ts
  src/templates-data/templates/cachet-db.ts
  src/templates-data/templates/canvas-db.ts
  src/templates-data/templates/doorkeeper-db.ts
  src/templates-data/templates/flarum-db.ts
  src/templates-data/templates/flipper-db.ts
  src/templates-data/templates/orchid-db.ts
  src/templates-data/templates/taggit-db.ts
Labels: enhancement

#400 fix(Last Saved): Translate the "last saved" relative date message
  src/pages/editor-page/top-navbar/last-saved.tsx
Labels: Translation

#457 feat(add templates): add six more templates
  src/assets/templates/deployer-db-dark.png
  src/assets/templates/deployer-db.png
  src/assets/templates/devise-db-dark.png
  src/assets/templates/devise-db.png
  src/assets/templates/reversion-db-dark.png
  src/assets/templates/reversion-db.png
  src/assets/templates/screeenly-db-dark.png
  src/assets/templates/screeenly-db.png
  src/assets/templates/staytus-db-dark.png
  src/assets/templates/staytus-db.png
  src/assets/templates/talk-db-dark.png
  src/assets/templates/talk-db.png
  src/templates-data/templates-data.ts
  src/templates-data/templates/deployer-db.ts
  src/templates-data/templates/devise-db.ts
  src/templates-data/templates/orchid-db.ts
  src/templates-data/templates/reversion-db.ts
  src/templates-data/templates/screeenly-db.ts
  src/templates-data/templates/staytus-db.ts
  src/templates-data/templates/talk-db.ts
Labels: enhancement

#456 fix(import-database): update database type after importing into an existing generic diagram
  src/dialogs/import-database-dialog/import-database-dialog.tsx
Labels: bug, ux

#459 feat(mariadb): Add uuid data type
  src/lib/data/data-types/mariadb-data-types.ts
Labels: bug

#432 feat(i18n): Added bangla translations
  src/i18n/i18n.ts
  src/i18n/locales/bn.ts
  src/pages/editor-page/top-navbar/last-saved.tsx
Labels: Translation

#460 feat(add templates): add six more templates (django-axes, laravel-activitylog, octobox, pay-rails, pixelfed, polr)
  src/assets/templates/django-axes-db-dark.png
  src/assets/templates/django-axes-db.png
  src/assets/templates/laravel-activitylog-db-dark.png
  src/assets/templates/laravel-activitylog-db.png
  src/assets/templates/octobox-db-dark.png
  src/assets/templates/octobox-db.png
  src/assets/templates/pay-rails-db-dark.png
  src/assets/templates/pay-rails-db.png
  src/assets/templates/pixelfed-db-dark.png
  src/assets/templates/pixelfed-db.png
  src/assets/templates/polr-db-dark.png
  src/assets/templates/polr-db.png
  src/templates-data/templates-data.ts
  src/templates-data/templates/django-axes-db.ts
  src/templates-data/templates/laravel-activitylog-db.ts
  src/templates-data/templates/octobox-db.ts
  src/templates-data/templates/pay-rails-db.ts
  src/templates-data/templates/pixelfed-db.ts
  src/templates-data/templates/polr-db.ts
Labels: enhancement
