Repository chartdb/chartdb, pull requests merged in 2025-01, with the labels that each got.

#512 chore(main): release 1.6.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#530 fix(chat-type): remove typo of char datatype in examples
  src/pages/examples-page/examples-data/examples-data.ts
  src/templates-data/templates/employee-db.ts
  src/templates-data/templates/visual-novel-db.ts
Labels: bug

#532 fix(filter-tables) show clean filter if no-results
  package-lock.json
  package.json
  src/i18n/locales/ar.ts
  src/i18n/locales/bn.ts
  src/i18n/locales/de.ts
  src/i18n/locales/en.ts
  src/i18n/locales/es.ts
  src/i18n/locales/fr.ts
  src/i18n/locales/gu.ts
  src/i18n/locales/hi.ts
  src/i18n/locales/id_ID.ts
  src/i18n/locales/ja.ts
  src/i18n/locales/ko_KR.ts
  src/i18n/locales/mr.ts
  src/i18n/locales/ne.ts
  src/i18n/locales/pt_BR.ts
  src/i18n/locales/ru.ts
  src/i18n/locales/te.ts
  src/i18n/locales/tr.ts
  src/i18n/locales/uk.ts
  src/i18n/locales/vi.ts
  src/i18n/locales/zh_CN.ts
  src/i18n/locales/zh_TW.ts
  src/pages/editor-page/side-panel/tables-section/tables-section.tsx
Labels: enhancement

#527 chore(main): release 1.6.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#529 fix(i18n): translation/Ukrainian
  src/i18n/locales/uk.ts
Labels: Translation

#534 feat(dbml-editor): add dbml editor in side pannel
  package-lock.json
  package.json
  src/components/code-snippet/code-snippet.tsx
  src/i18n/locales/ar.ts
  src/i18n/locales/bn.ts
  src/i18n/locales/de.ts
  src/i18n/locales/en.ts
  src/i18n/locales/es.ts
  src/i18n/locales/fr.ts
  src/i18n/locales/gu.ts
  src/i18n/locales/hi.ts
  src/i18n/locales/id_ID.ts
  src/i18n/locales/ja.ts
  src/i18n/locales/ko_KR.ts
  src/i18n/locales/mr.ts
  src/i18n/locales/ne.ts
  src/i18n/locales/pt_BR.ts
  src/i18n/locales/ru.ts
  src/i18n/locales/te.ts
  src/i18n/locales/tr.ts
  src/i18n/locales/uk.ts
  src/i18n/locales/vi.ts
  src/i18n/locales/zh_CN.ts
  src/i18n/locales/zh_TW.ts
  src/lib/data/data-types/data-types.ts
  src/pages/editor-page/side-panel/tables-section/table-dbml/table-dbml.tsx
  src/pages/editor-page/side-panel/tables-section/tables-section.tsx
Labels: enhancement

#546 fix(psql-import): remove typo for import command (psql)
  src/lib/data/import-metadata/scripts/postgres-script.ts
Labels: bug
