Repository chartdb/chartdb, pull requests merged in 2025-09, with the labels that each got.

#897 fix(sql-import): handle SQL Server DDL with multiple tables, inline foreign keys, and case-insensitive field matching
  src/lib/data/sql-import/common.ts
  src/lib/data/sql-import/dialect-importers/sqlserver/__tests__/sqlserver-exact-user-case.test.ts
  src/lib/data/sql-import/dialect-importers/sqlserver/__tests__/sqlserver-full-flow.test.ts
  src/lib/data/sql-import/dialect-importers/sqlserver/__tests__/sqlserver-multi-table-fk.test.ts
  src/lib/data/sql-import/dialect-importers/sqlserver/__tests__/sqlserver-verify-fk.test.ts
  src/lib/data/sql-import/dialect-importers/sqlserver/sqlserver.ts
Labels: bug

#907 refactor: remove dedicated DBML import dialog
  src/context/dialog-context/dialog-context.tsx
  src/context/dialog-context/dialog-provider.tsx
  src/dialogs/common/import-database/import-database.tsx
  src/dialogs/create-diagram-dialog/create-diagram-dialog.tsx
  src/dialogs/import-dbml-dialog/import-dbml-dialog.tsx
  src/pages/editor-page/top-navbar/menu/menu.tsx
Labels: enhancement

#918 feat: add area context menu and UI improvements
  src/pages/editor-page/canvas/area-node/area-node-context-menu.tsx
  src/pages/editor-page/canvas/area-node/area-node.tsx
  src/pages/editor-page/top-navbar/diagram-name.tsx
Labels: enhancement

#881 chore(main): release 1.16.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending
