Repository chartdb/chartdb, pull requests merged in 2025-03, with the labels that each got.

#581 chore(main): release 1.8.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#602 fix(shorcuts): add shortcut to toggle the theme
  src/context/keyboard-shortcuts-context/keyboard-shortcuts.ts
  src/context/theme-context/theme-provider.tsx
  src/pages/editor-page/top-navbar/menu/menu.tsx
Labels: enhancement

#607 chore(main): release 1.9.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#624 fix(dbml-editor): dealing with dbml editor for non-generic db-type
  src/lib/data/export-metadata/export-sql-script.ts
  src/pages/editor-page/side-panel/tables-section/table-dbml/table-dbml.tsx
Labels: bug

#632 feat(cloudflare-d1): add support to cloudflare-d1 + wrangler cli
  README.md
  src/assets/cloudflare_d1.png
  src/dialogs/common/import-database/import-database.tsx
  src/dialogs/create-diagram-dialog/create-diagram-dialog.tsx
  src/dialogs/import-database-dialog/import-database-dialog.tsx
  src/lib/data/import-metadata/scripts/scripts.ts
  src/lib/data/import-metadata/scripts/sqlite-script.ts
  src/lib/domain/database-clients.ts
  src/lib/domain/database-edition.ts
Labels: enhancement

#619 chore(main): release 1.10.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending
