Repository chartdb/chartdb, pull requests merged in 2025-08, with the labels that each got.

#834 fix: for sqlite import - add more types & include type parameters
  src/lib/data/data-types/sqlite-data-types.ts
  src/lib/data/export-metadata/export-per-type/sqlite.ts
Labels: bug

#812 feat(postgres): add support hash index types
  src/context/diagram-filter-context/diagram-filter-provider.tsx
  src/i18n/locales/ar.ts
  src/i18n/locales/bn.ts
  src/i18n/locales/de.ts
  src/i18n/locales/en.ts
  src/i18n/locales/es.ts
  src/i18n/locales/fr.ts
  src/i18n/locales/gu.ts
  src/i18n/locales/hi.ts
  src/i18n/locales/hr.ts
  src/i18n/locales/id_ID.ts
  src/i18n/locales/ja.ts
  src/i18n/locales/ko_KR.ts
  src/i18n/locales/mr.ts
  src/i18n/locales/ne.ts
  src/i18n/locales/pt_BR.ts
  src/i18n/locales/ru.ts
  src/i18n/locales/te.ts
  src/i18n/locales/tr.ts
  src/i18n/locales/uk.ts
  src/i18n/locales/vi.ts
  src/i18n/locales/zh_CN.ts
  src/i18n/locales/zh_TW.ts
  src/lib/data/export-metadata/export-per-type/postgresql.ts
  src/lib/domain/db-index.ts
  src/pages/editor-page/canvas/canvas-filter/canvas-filter.tsx
  src/pages/editor-page/side-panel/tables-section/table-list/table-list-item/table-list-item-content/table-index/table-index.tsx
Labels: enhancement

#852 fix: DBML export error with multi-line table comments for SQL Server
  src/lib/data/export-metadata/export-sql-script.ts
  src/lib/domain/database-type.ts
Labels: bug

#851 feat: add auto increment support for fields with database-specific export
  src/i18n/locales/ar.ts
  src/i18n/locales/bn.ts
  src/i18n/locales/de.ts
  src/i18n/locales/en.ts
  src/i18n/locales/es.ts
  src/i18n/locales/fr.ts
  src/i18n/locales/gu.ts
  src/i18n/locales/hi.ts
  src/i18n/locales/hr.ts
  src/i18n/locales/id_ID.ts
  src/i18n/locales/ja.ts
  src/i18n/locales/ko_KR.ts
  src/i18n/locales/mr.ts
  src/i18n/locales/ne.ts
  src/i18n/locales/pt_BR.ts
  src/i18n/locales/ru.ts
  src/i18n/locales/te.ts
  src/i18n/locales/tr.ts
  src/i18n/locales/uk.ts
  src/i18n/locales/vi.ts
  src/i18n/locales/zh_CN.ts
  src/i18n/locales/zh_TW.ts
  src/lib/data/data-types/data-types.ts
  src/lib/data/export-metadata/export-per-type/mssql.ts
  src/lib/data/export-metadata/export-per-type/mysql.ts
  src/lib/data/export-metadata/export-per-type/sqlite.ts
  src/lib/data/export-metadata/export-sql-script.ts
  src/pages/editor-page/side-panel/tables-section/table-list/table-list-item/table-list-item-content/table-field/table-field-modal/table-field-modal.tsx
Labels: enhancement

#869 fix: preserve composite primary key constraint names across import/export workflows
  src/context/chartdb-context/chartdb-provider.tsx
  src/lib/data/export-metadata/__tests__/export-sql-dbml.test.ts
  src/lib/data/export-metadata/export-per-type/mssql.ts
  src/lib/data/export-metadata/export-per-type/mysql.ts
  src/lib/data/export-metadata/export-per-type/postgresql.ts
  src/lib/data/export-metadata/export-sql-script.ts
  src/lib/dbml/dbml-export/__tests__/composite-pk-export.test.ts
  src/lib/dbml/dbml-export/__tests__/dbml-export-issue-fix.test.ts
  src/lib/dbml/dbml-export/dbml-export.ts
  src/lib/dbml/dbml-import/__tests__/composite-pk-name.test.ts
  src/lib/dbml/dbml-import/__tests__/dbml-import-fantasy-examples.test.ts
  src/lib/dbml/dbml-import/dbml-import.ts
  src/lib/domain/__tests__/composite-pk-metadata-import.test.ts
  src/lib/domain/db-index.ts
  src/lib/domain/db-table.ts
  src/pages/editor-page/side-panel/tables-section/table-list/table-list-item/table-list-item-content/table-index/table-index.tsx
  src/pages/editor-page/side-panel/tables-section/table-list/table-list-item/table-list-item-content/table-list-item-content.tsx
Labels: bug

#878 chore(main): release 1.15.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending
