Repository chartdb/chartdb, pull requests merged in 2025-02, with the labels that each got.

#547 fix(empty-state): fix dark-mode for empty-state
  src/assets/empty_state_dark.png
  src/components/empty-state/empty-state.tsx
Labels: bug

#549 feat(import-dbml): add import dbml functionality
  src/components/code-snippet/languages/dbml-language.ts
  src/context/canvas-context/canvas-context.tsx
  src/context/canvas-context/canvas-provider.tsx
  src/context/dialog-context/dialog-context.tsx
  src/context/dialog-context/dialog-provider.tsx
  src/dialogs/import-dbml-dialog/import-dbml-dialog.tsx
  src/hooks/use-canvas.ts
  src/i18n/locales/ar.ts
  src/i18n/locales/bn.ts
  src/i18n/locales/de.ts
  src/i18n/locales/en.ts
  src/i18n/locales/es.ts
  src/i18n/locales/fr.ts
  src/i18n/locales/gu.ts
  src/i18n/locales/hi.ts
  src/i18n/locales/id_ID.ts
  src/i18n/locales/ja.ts
  src/i18n/locales/ko_KR.ts
  src/i18n/locales/mr.ts
  src/i18n/locales/ne.ts
  src/i18n/locales/pt_BR.ts
  src/i18n/locales/ru.ts
  src/i18n/locales/te.ts
  src/i18n/locales/tr.ts
  src/i18n/locales/uk.ts
  src/i18n/locales/vi.ts
  src/i18n/locales/zh_CN.ts
  src/i18n/locales/zh_TW.ts
  src/lib/dbml-import.ts
  src/pages/editor-page/canvas/canvas.tsx
  src/pages/editor-page/editor-page.tsx
  src/pages/editor-page/side-panel/tables-section/table-dbml/table-dbml.tsx
  src/pages/editor-page/top-navbar/menu/menu.tsx
Labels: enhancement

#535 fix(dbml-editor): add shortcuts to dbml and filter: #534
  src/pages/editor-page/side-panel/tables-section/tables-section.tsx
Labels: enhancement

#539 chore(main): release 1.7.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#543 feat(docker image): add support for custom inference servers
  Dockerfile
  README.md
  default.conf.template
  entrypoint.sh
  src/lib/data/export-metadata/export-sql-script.ts
  src/lib/env.ts
Labels: enhancement

#556 feat(dbml-import): add error highlighting for dbml imports
  src/dialogs/import-dbml-dialog/import-dbml-dialog.tsx
  src/globals.css
  src/i18n/locales/ar.ts
  src/i18n/locales/bn.ts
  src/i18n/locales/de.ts
  src/i18n/locales/en.ts
  src/i18n/locales/es.ts
  src/i18n/locales/fr.ts
  src/i18n/locales/gu.ts
  src/i18n/locales/hi.ts
  src/i18n/locales/id_ID.ts
  src/i18n/locales/ja.ts
  src/i18n/locales/ko_KR.ts
  src/i18n/locales/mr.ts
  src/i18n/locales/ne.ts
  src/i18n/locales/pt_BR.ts
  src/i18n/locales/ru.ts
  src/i18n/locales/te.ts
  src/i18n/locales/tr.ts
  src/i18n/locales/uk.ts
  src/i18n/locales/vi.ts
  src/i18n/locales/zh_CN.ts
  src/i18n/locales/zh_TW.ts
Labels: enhancement

#562 fix(import-query): improve the cleanup for messy json input
  src/lib/data/import-metadata/utils.ts
Labels: bug

#561 fix(realtionships-fk): add the schema to source/target tables
  src/pages/editor-page/side-panel/relationships-section/relationship-list/relationship-list-item/relationship-list-item-content/relationship-list-item-content.tsx
Labels: enhancement

#566 fix(import dbml): add import for indexes
  src/lib/dbml-import.ts
Labels: enhancement

#568 fix(canvas): add right-click option to create relationships
  src/context/dialog-context/dialog-context.tsx
  src/context/dialog-context/dialog-provider.tsx
  src/dialogs/create-relationship-dialog/create-relationship-dialog.tsx
  src/i18n/locales/ar.ts
  src/i18n/locales/bn.ts
  src/i18n/locales/de.ts
  src/i18n/locales/en.ts
  src/i18n/locales/es.ts
  src/i18n/locales/fr.ts
  src/i18n/locales/gu.ts
  src/i18n/locales/hi.ts
  src/i18n/locales/id_ID.ts
  src/i18n/locales/ja.ts
  src/i18n/locales/ko_KR.ts
  src/i18n/locales/mr.ts
  src/i18n/locales/ne.ts
  src/i18n/locales/pt_BR.ts
  src/i18n/locales/ru.ts
  src/i18n/locales/te.ts
  src/i18n/locales/tr.ts
  src/i18n/locales/uk.ts
  src/i18n/locales/vi.ts
  src/i18n/locales/zh_CN.ts
  src/i18n/locales/zh_TW.ts
  src/pages/editor-page/canvas/table-node/table-node-context-menu.tsx
Labels: enhancement

#565 fix(sqlserver-import): open ssms guide when max chars
  src/dialogs/common/import-database/import-database.tsx
  src/dialogs/common/import-database/ssms-info/ssms-info.tsx
Labels: bug

#570 fix(export-sql): show create script for only filtered schemas
  src/dialogs/export-sql-dialog/export-sql-dialog.tsx
Labels: enhancement

#572 fix(mssql-import): improve script readability by adding edition comment
  src/lib/data/import-metadata/scripts/sqlserver-script.ts
Labels: documentation

#558 chore(main): release 1.8.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#574 fix(empty-state): show diff buttons on import-dbml when triggered by empty
  src/context/dialog-context/dialog-context.tsx
  src/context/dialog-context/dialog-provider.tsx
  src/dialogs/create-diagram-dialog/create-diagram-dialog.tsx
  src/dialogs/import-dbml-dialog/import-dbml-dialog.tsx
  src/i18n/locales/ar.ts
  src/i18n/locales/bn.ts
  src/i18n/locales/de.ts
  src/i18n/locales/en.ts
  src/i18n/locales/es.ts
  src/i18n/locales/fr.ts
  src/i18n/locales/gu.ts
  src/i18n/locales/hi.ts
  src/i18n/locales/id_ID.ts
  src/i18n/locales/ja.ts
  src/i18n/locales/ko_KR.ts
  src/i18n/locales/mr.ts
  src/i18n/locales/ne.ts
  src/i18n/locales/pt_BR.ts
  src/i18n/locales/ru.ts
  src/i18n/locales/te.ts
  src/i18n/locales/tr.ts
  src/i18n/locales/uk.ts
  src/i18n/locales/vi.ts
  src/i18n/locales/zh_CN.ts
  src/i18n/locales/zh_TW.ts
Labels: enhancement

#571 fix(sqlite-import) import nuallable columns correctly + add json type
  src/lib/data/data-types/sqlite-data-types.ts
  src/lib/data/import-metadata/scripts/sqlite-script.ts
Labels: bug

#579 (i18n): add [FR] translation
  src/i18n/locales/fr.ts
Labels: Translation

#573 fix(side-panel): simplify how to add field and index
  src/pages/editor-page/side-panel/tables-section/table-list/table-list-item/table-list-item-content/table-list-item-content.tsx
Labels: enhancement

#588 fix(img-export): add ChartDB watermark to exported image
  src/context/export-image-context/export-image-provider.tsx
Labels: enhancement

#590 fix(menu-backup): update export to be backup
  src/i18n/locales/ar.ts
  src/i18n/locales/bn.ts
  src/i18n/locales/de.ts
  src/i18n/locales/en.ts
  src/i18n/locales/es.ts
  src/i18n/locales/fr.ts
  src/i18n/locales/gu.ts
  src/i18n/locales/hi.ts
  src/i18n/locales/id_ID.ts
  src/i18n/locales/ja.ts
  src/i18n/locales/ko_KR.ts
  src/i18n/locales/mr.ts
  src/i18n/locales/ne.ts
  src/i18n/locales/pt_BR.ts
  src/i18n/locales/ru.ts
  src/i18n/locales/te.ts
  src/i18n/locales/tr.ts
  src/i18n/locales/uk.ts
  src/i18n/locales/vi.ts
  src/i18n/locales/zh_CN.ts
  src/i18n/locales/zh_TW.ts
  src/pages/editor-page/top-navbar/menu/menu.tsx
Labels: enhancement

#597 feat(add-docs): add link to ChartDB documentation
  src/i18n/locales/ar.ts
  src/i18n/locales/bn.ts
  src/i18n/locales/de.ts
  src/i18n/locales/en.ts
  src/i18n/locales/es.ts
  src/i18n/locales/fr.ts
  src/i18n/locales/gu.ts
  src/i18n/locales/hi.ts
  src/i18n/locales/id_ID.ts
  src/i18n/locales/ja.ts
  src/i18n/locales/ko_KR.ts
  src/i18n/locales/mr.ts
  src/i18n/locales/ne.ts
  src/i18n/locales/pt_BR.ts
  src/i18n/locales/ru.ts
  src/i18n/locales/te.ts
  src/i18n/locales/tr.ts
  src/i18n/locales/uk.ts
  src/i18n/locales/vi.ts
  src/i18n/locales/zh_CN.ts
  src/i18n/locales/zh_TW.ts
  src/pages/editor-page/top-navbar/menu/menu.tsx
Labels: enhancement

#598 fix(import-mssql): fix import/export scripts to handle data correctly
  src/lib/data/export-metadata/export-per-type/common.ts
  src/lib/data/export-metadata/export-per-type/mssql.ts
  src/lib/data/export-metadata/export-sql-script.ts
  src/lib/data/import-metadata/scripts/sqlserver-script.ts
Labels: bug
