Repository chartdb/chartdb, pull requests merged in 2025-05, with the labels that each got.

#687 fix(dbml-editor): add inline refs mode + fix issues with DBML syntax
  src/components/code-snippet/code-snippet.tsx
  src/lib/data/export-metadata/export-sql-script.ts
  src/pages/editor-page/side-panel/tables-section/table-dbml/table-dbml.tsx
Labels: enhancement

#690 fix(translations): Add some translations for ru-RU language
  src/dialogs/import-dbml-dialog/import-dbml-dialog.tsx
  src/i18n/locales/ru.ts
Labels: Translation

#696 fix(ddl-import): fix datatypes when importing via ddl
  src/lib/data/data-types/sqlite-data-types.ts
  src/lib/data/sql-import/common.ts
  src/lib/data/sql-import/dialect-importers/sqlite/sqlite.ts
Labels: bug

#684 fix(dependencies): hide icon when diagram has no dependencies
  src/pages/editor-page/editor-sidebar/editor-sidebar.tsx
  src/pages/editor-page/top-navbar/menu/menu.tsx
Labels: enhancement

#697 fix(import-json): for broken json imports
  src/dialogs/common/import-database/import-database.tsx
  src/lib/data/import-metadata/utils.ts
Labels: bug

#700 fix(postgres): fix import of postgres fks
  src/lib/data/export-metadata/export-per-type/postgresql.ts
  src/lib/data/sql-import/common.ts
  src/lib/data/sql-import/dialect-importers/postgresql/postgresql.ts
  src/lib/domain/db-field.ts
Labels: bug

#699 fix(import): dbml and query - senetize before import
  src/dialogs/import-dbml-dialog/import-dbml-dialog.tsx
  src/lib/data/import-metadata/utils.ts
  src/lib/dbml-import.ts
Labels: bug

#701 fix(ddl): inline fks ddl script
  src/lib/data/sql-import/common.ts
  src/lib/data/sql-import/dialect-importers/mysql/mysql.ts
  src/lib/data/sql-import/dialect-importers/postgresql/postgresql.ts
Labels: bug

#702 fix(import-database): remove view_definition when importing via query
  src/dialogs/common/import-database/instructions-section/instructions/smart-query-instructions.tsx
  src/lib/data/import-metadata/scripts/cockroachdb-script.ts
  src/lib/data/import-metadata/scripts/maria-script.ts
  src/lib/data/import-metadata/scripts/minimize-script.ts
  src/lib/data/import-metadata/scripts/mysql-script.ts
  src/lib/data/import-metadata/scripts/postgres-script.ts
  src/lib/data/import-metadata/scripts/sqlserver-script.ts
  src/lib/data/import-metadata/utils.ts
Labels: bug

#707 fix(expanded-table): persist expanded state across renders
  src/lib/domain/db-table.ts
  src/pages/editor-page/canvas/canvas-utils.ts
  src/pages/editor-page/canvas/canvas.tsx
  src/pages/editor-page/canvas/table-node/table-node.tsx
Labels: bug

#710 fix(sql-script): change ddl to be sql-script
  src/dialogs/common/import-database/import-database.tsx
  src/dialogs/common/import-database/instructions-section/instructions-section.tsx
  src/i18n/locales/ar.ts
  src/i18n/locales/bn.ts
  src/i18n/locales/de.ts
  src/i18n/locales/en.ts
  src/i18n/locales/es.ts
  src/i18n/locales/fr.ts
  src/i18n/locales/gu.ts
  src/i18n/locales/hi.ts
  src/i18n/locales/id_ID.ts
  src/i18n/locales/ja.ts
  src/i18n/locales/ko_KR.ts
  src/i18n/locales/mr.ts
  src/i18n/locales/ne.ts
  src/i18n/locales/pt_BR.ts
  src/i18n/locales/ru.ts
  src/i18n/locales/te.ts
  src/i18n/locales/tr.ts
  src/i18n/locales/uk.ts
  src/i18n/locales/vi.ts
  src/i18n/locales/zh_CN.ts
  src/i18n/locales/zh_TW.ts
Labels: documentation

#662 chore(main): release 1.12.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#718 fix(import-database): remove the default fetch from import database
  src/lib/data/import-metadata/scripts/clickhouse-script.ts
  src/lib/data/import-metadata/scripts/cockroachdb-script.ts
  src/lib/data/import-metadata/scripts/maria-script.ts
  src/lib/data/import-metadata/scripts/mysql-script.ts
  src/lib/data/import-metadata/scripts/oracle-script.ts
  src/lib/data/import-metadata/scripts/postgres-script.ts
  src/lib/data/import-metadata/scripts/sqlite-script.ts
  src/lib/data/import-metadata/scripts/sqlserver-script.ts
Labels: bug

#728 fix(dbml-editor): export comments with schema if exists
  src/pages/editor-page/side-panel/tables-section/table-dbml/table-dbml.tsx
Labels: bug
