Repository chartdb/chartdb, pull requests merged in 2025-04, with the labels that each got.

#639 feat(import-sql): import postgresql via SQL (DDL script)
  src/dialogs/common/import-database/import-database.tsx
  src/dialogs/common/import-database/instructions-section/instructions-section.tsx
  src/dialogs/common/import-database/instructions-section/instructions/ddl-instruction-step.tsx
  src/dialogs/common/import-database/instructions-section/instructions/ddl-instructions.tsx
  src/dialogs/common/import-database/instructions-section/instructions/smart-query-instructions.tsx
  src/dialogs/common/import-database/instructions-section/instructions/ssms-info/ssms-info.tsx
  src/dialogs/create-diagram-dialog/create-diagram-dialog.tsx
  src/dialogs/import-database-dialog/import-database-dialog.tsx
  src/i18n/locales/en.ts
  src/lib/data/sql-import/common.ts
  src/lib/data/sql-import/dialect-importers/mysql/mysql-common.ts
  src/lib/data/sql-import/dialect-importers/mysql/mysql.ts
  src/lib/data/sql-import/dialect-importers/postgresql/postgresql-common.ts
  src/lib/data/sql-import/dialect-importers/postgresql/postgresql-dump.ts
  src/lib/data/sql-import/dialect-importers/postgresql/postgresql.ts
  src/lib/data/sql-import/dialect-importers/sqlite/sqlite-common.ts
  src/lib/data/sql-import/dialect-importers/sqlite/sqlite.ts
  src/lib/data/sql-import/dialect-importers/sqlserver/sqlserver-common.ts
  src/lib/data/sql-import/dialect-importers/sqlserver/sqlserver.ts
  src/lib/data/sql-import/index.ts
Labels: enhancement

#637 chore(main): release 1.11.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#651 fix: add sorting based on how common the datatype on side-panel
  src/components/select-box/select-box.tsx
  src/lib/data/data-types/data-types.ts
  src/lib/data/data-types/generic-data-types.ts
  src/lib/data/data-types/mariadb-data-types.ts
  src/lib/data/data-types/mysql-data-types.ts
  src/lib/data/data-types/postgres-data-types.ts
  src/lib/data/data-types/sql-server-data-types.ts
  src/lib/data/data-types/sqlite-data-types.ts
  src/pages/editor-page/side-panel/tables-section/table-list/table-list-item/table-list-item-content/table-field/table-field.tsx
Labels: enhancement

#677 fix(examples): update examples to have areas
  src/assets/examples/bike_stores_example.png
  src/assets/examples/bike_stores_example_dark.png
  src/assets/examples/dvd_rental_example.png
  src/assets/examples/dvd_rental_example_dark.png
  src/assets/examples/employees_example.png
  src/assets/examples/employees_example_dark.png
  src/pages/examples-page/examples-data/examples-data.ts
Labels: enhancement

#681 fix(import-json): simplify import script for fixing invalid JSON
  src/dialogs/common/import-database/import-database.tsx
Labels: ux

#683 fix(dbml-editor): remove invalid fields before showing DBML + warning
  src/pages/editor-page/side-panel/tables-section/table-dbml/table-dbml.tsx
Labels: bug
